---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hughboi
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: hughboi-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.hughboi.vip"
  dnsNames:
  - "*.hughboi.vip"
  - hughboi.vip
